### ISSUE TITLE
How track the dependencies?

### ISSUE THREAD

**Issue by SeanSilke** [th0r/webpack-bundle-analyzer#109] opened 2017-08-01 19:31 UTC
Hello! 
  I was analizing my bundel and was confuse to find some
big libs on top leve, despite i new use them in my project.
After some reasers i found that that libs was in dependenses
of lib that I use directly.
So.
   Why some of libs that was not directly imported but is in
dependencies of other libraries end up on top level?
Is there the way define who is dependent on particular
lib and why it end up in bundle?

**Comment by valscion** [comment] 2017-08-02 06:01
Could you send a screenshot of your analyzer browser view so we could see what you mean by top level? Thanks!

**Comment by SeanSilke** [comment] 2017-08-02 10:42
Here  moments.js and hammer.js is used only by Vis.js.
<img width="732" alt="vis deps aug 02 13-39-21" src="https://user-images.githubusercontent.com/1077074/28870203-1571fcac-7788-11e7-9ad8-0afc8b444878.png">

**Comment by valscion** [comment] 2017-08-02 18:15
Thanks for the extra explanation! Unfortunately, such feature is not yet possible. This issue is a duplicate of #53 so I'll close this one.

**Closed by valscion** 2017-08-02 18:15 UTC

**Comment by SeanSilke** [comment] 2017-08-02 19:26
@valscion got it thanks.
