### ISSUE TITLE
Port error when using in webpack --watch mode

### ISSUE THREAD

**Issue by nashwaan** [th0r/webpack-bundle-analyzer#73] opened 2017-05-11 02:56 UTC
Thanks @th0r for this great analyzer tool.

I tried to use this plugin in webpack --watch mode but when I do changes to my project and save, webpack crashes and shows error that the port already in use. I guess the tool tries to open a new web page and establish a new 8888 port rather than connecting to existing 8888 port and refresh the result. Any help on this?

**Comment by valscion** [comment] 2017-05-11 07:32
Thanks for the issue! This seems to be a duplicate of #37 so I'll close this.

**Closed by valscion** 2017-05-11 07:32 UTC
